language: csharp
solution: Oware.sln
mono: none
script:
 - dotnet test
jobs:
 include:
  - os: linux
    dist: focal
    dotnet: 3.1.301
  - os: osx
    osx_image: xcode11.5
    dotnet: 3.1.301
